# Generated by Django 4.0 on 2022-01-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
