# Generated by Django 4.0 on 2022-01-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0002_drivers_delete_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drivers',
            new_name='Driver',
        ),
    ]
