# Generated by Django 4.0 on 2022-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0005_forum_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_created_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
