# Generated by Django 4.0 on 2022-01-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Site_app', '0007_alter_forum_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='user_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='User_created_comment',
        ),
    ]
