# Generated by Django 4.0 on 2022-01-20 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Site_app', '0008_alter_forum_user_name_delete_user_created_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='user_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
