# Generated by Django 4.0 on 2022-01-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0010_user_created_comment_alter_forum_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Site_app.user_created_comment'),
        ),
    ]
