# Generated by Django 4.0 on 2022-01-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0012_alter_forum_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_created_comment',
        ),
        migrations.AlterField(
            model_name='forum',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
