# Generated by Django 4.0 on 2022-01-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0013_delete_user_created_comment_alter_forum_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='score',
        ),
    ]
