# Generated by Django 4.0 on 2022-12-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_app', '0021_remove_driver_year_driver_year_delete_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='year',
        ),
        migrations.AddField(
            model_name='driver',
            name='year',
            field=models.ManyToManyField(to='Site_app.Year'),
        ),
    ]
